### ISSUE TITLE
feature request: playground preview

### ISSUE THREAD

**Issue by siegebell** [SrTobi/code-pegjs-language#2]
Thanks for writing this extension!

Anyhow, if you're looking to add more features, it would be nice to have the equivalent of http://pegjs.org/online in vscode. E.g. when editing a pegjs script, bind `ctrl+k v`/`ctrl+shift+v` (open preview) to a command that launches the equivalent of the right panel of the online playground, using `TextDocumentContentProvider` and `previewHtml`.

This way, I won't have to copy & paste between vscode and http://pegjs.org/online all the time to test my grammar, and it can be specific to the the version of pegjs installed.

**Comment by SrTobi** [comment]
Nice idea 👍 I remember to having something like that in mind as well when I wrote this extension. Unfortunately currently I do not have time and don't feel like it. But that shouldn't stop you 😄   feel free to fork, code and PR back.

**Comment by Telokis** [comment]
@SrTobi Could you let this issue open until someone implements it, please?

**Comment by SrTobi** [comment]
sure
