### ISSUE TITLE
Keywords breaking highlighting in OMeta

### ISSUE THREAD

**Issue by DazEdword** [SrTobi/code-pegjs-language#3]
Literals of certain words (found out that I can reproduce this bug with a rule such as keyword = ``interface'', ) mess up with large chunks of the grammar's syntax highlighting immediately after the keyword is used. As a curiosity (and workaround, too), know that you can use a commented opening curly brace (//{) in the lines preceding the broken syntax section to bring back colorization. 

Tested in Visual Studio Code 1.8.1, PEGjs 0.1.0 and an OMetaJS .ojs grammar.

**Comment by SrTobi** [comment]
I am not fully sure what you mean... could you post some lines of code as an example showing the problem?

**Comment by DazEdword** [comment]
Sure I can : ). 

1.- Messed syntax highlighting due (probably?) to said problem with the keyword. 
![code_2016-12-20_10-06-13](https://cloud.githubusercontent.com/assets/10813745/21346365/0927d446-c69c-11e6-9b56-9b5f2ddee72a.png)

2.- Same code showing properly, without the keyword. 
![code_2016-12-20_10-07-45](https://cloud.githubusercontent.com/assets/10813745/21346423/3ac7d3a2-c69c-11e6-952f-fb75582351f8.png)

3.- Commented braces workaround.
![code_2016-12-20_10-08-50](https://cloud.githubusercontent.com/assets/10813745/21346468/60e77826-c69c-11e6-8154-76dbe1a965e3.png)

I'm pretty sure that bug occurs due to other keywords too (I'm suspicious of "class"), but I haven't checked out that yet. 

Hope that helps!

**Comment by SrTobi** [comment]
Hmm, I probably are making a logical mistake here, but for me it seems, that you are try to highlight a OMetaJS grammar... which is - as far as I can see - not related to peg.js in any way (though I don't know OMetaJS). This plugin is for highlighting peg.js grammars which are different.

**Comment by DazEdword** [comment]
Yes, you are right in indeed I am aware it is two different things here, though they are similar enough to the point of the extension being perfectly usable with OMetaJS. I'll try to take a look at this too, in case I can fix this bug or adapt it to OMetaJS.
