### ISSUE TITLE
Jump to production feature request

### ISSUE THREAD

**Issue by AndrewRayCode** [SrTobi/code-pegjs-language#6]
Hi, thanks for this plugin! The error highlighting is great, it's helped me catch typos. One thing that would also be super helpful is jumping to a production, like control/command click to jump to source. If find the time and motivation I'd also love to try adding that feature to this plugin.

**Comment by SrTobi** [comment]
Hi @AndrewRayCode, thanks for the suggestion but there is actually a fork of this extension that already does that. you can find it [here](https://marketplace.visualstudio.com/items?itemName=PeggyJS.peggy-language). [Peggy](https://github.com/peggyjs/peggy) is the successor of peg.js and until now they are compatible. I think it would be good to migrate to peggy, which has active development now. The extensions has great features like find usages, goto definition, error highlighting, and even completion.
